# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ConfigDB.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ConfigDB.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0e\x43onfigDB.proto\"t\n\x0b\x43onfigValue\x12\x14\n\nvalue_bool\x18\x01 \x01(\x08H\x00\x12\x16\n\x0cvalue_uint32\x18\x02 \x01(\rH\x00\x12\x15\n\x0bvalue_int32\x18\x03 \x01(\x05H\x00\x12\x17\n\rvalue_float32\x18\x04 \x01(\x02H\x00\x42\x07\n\x05value\"D\n\x13\x43onfigDBSetEntryReq\x12\x10\n\x08\x65ntry_id\x18\x01 \x02(\r\x12\x1b\n\x05value\x18\x02 \x02(\x0b\x32\x0c.ConfigValue\"\'\n\x13\x43onfigDBGetEntryReq\x12\x10\n\x08\x65ntry_id\x18\x01 \x02(\r\"0\n\x1c\x43onfigDBSetEntryToDefaultReq\x12\x10\n\x08\x65ntry_id\x18\x01 \x02(\r\"w\n\x13\x43onfigEntryDataResp\x12\x10\n\x08\x65ntry_id\x18\x01 \x02(\r\x12\x1b\n\x05value\x18\x02 \x02(\x0b\x32\x0c.ConfigValue\x12#\n\rdefault_value\x18\x03 \x02(\x0b\x32\x0c.ConfigValue\x12\x0c\n\x04name\x18\x04 \x02(\t\"9\n\x10\x43onfigDBInfoResp\x12\x14\n\x0cnum_elements\x18\x01 \x02(\r\x12\x0f\n\x07version\x18\x02 \x02(\r'
)




_CONFIGVALUE = _descriptor.Descriptor(
  name='ConfigValue',
  full_name='ConfigValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='value_bool', full_name='ConfigValue.value_bool', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_uint32', full_name='ConfigValue.value_uint32', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_int32', full_name='ConfigValue.value_int32', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value_float32', full_name='ConfigValue.value_float32', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='value', full_name='ConfigValue.value',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=18,
  serialized_end=134,
)


_CONFIGDBSETENTRYREQ = _descriptor.Descriptor(
  name='ConfigDBSetEntryReq',
  full_name='ConfigDBSetEntryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_id', full_name='ConfigDBSetEntryReq.entry_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ConfigDBSetEntryReq.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=136,
  serialized_end=204,
)


_CONFIGDBGETENTRYREQ = _descriptor.Descriptor(
  name='ConfigDBGetEntryReq',
  full_name='ConfigDBGetEntryReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_id', full_name='ConfigDBGetEntryReq.entry_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=245,
)


_CONFIGDBSETENTRYTODEFAULTREQ = _descriptor.Descriptor(
  name='ConfigDBSetEntryToDefaultReq',
  full_name='ConfigDBSetEntryToDefaultReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_id', full_name='ConfigDBSetEntryToDefaultReq.entry_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=247,
  serialized_end=295,
)


_CONFIGENTRYDATARESP = _descriptor.Descriptor(
  name='ConfigEntryDataResp',
  full_name='ConfigEntryDataResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='entry_id', full_name='ConfigEntryDataResp.entry_id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='ConfigEntryDataResp.value', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_value', full_name='ConfigEntryDataResp.default_value', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='ConfigEntryDataResp.name', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=416,
)


_CONFIGDBINFORESP = _descriptor.Descriptor(
  name='ConfigDBInfoResp',
  full_name='ConfigDBInfoResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='num_elements', full_name='ConfigDBInfoResp.num_elements', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='version', full_name='ConfigDBInfoResp.version', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=418,
  serialized_end=475,
)

_CONFIGVALUE.oneofs_by_name['value'].fields.append(
  _CONFIGVALUE.fields_by_name['value_bool'])
_CONFIGVALUE.fields_by_name['value_bool'].containing_oneof = _CONFIGVALUE.oneofs_by_name['value']
_CONFIGVALUE.oneofs_by_name['value'].fields.append(
  _CONFIGVALUE.fields_by_name['value_uint32'])
_CONFIGVALUE.fields_by_name['value_uint32'].containing_oneof = _CONFIGVALUE.oneofs_by_name['value']
_CONFIGVALUE.oneofs_by_name['value'].fields.append(
  _CONFIGVALUE.fields_by_name['value_int32'])
_CONFIGVALUE.fields_by_name['value_int32'].containing_oneof = _CONFIGVALUE.oneofs_by_name['value']
_CONFIGVALUE.oneofs_by_name['value'].fields.append(
  _CONFIGVALUE.fields_by_name['value_float32'])
_CONFIGVALUE.fields_by_name['value_float32'].containing_oneof = _CONFIGVALUE.oneofs_by_name['value']
_CONFIGDBSETENTRYREQ.fields_by_name['value'].message_type = _CONFIGVALUE
_CONFIGENTRYDATARESP.fields_by_name['value'].message_type = _CONFIGVALUE
_CONFIGENTRYDATARESP.fields_by_name['default_value'].message_type = _CONFIGVALUE
DESCRIPTOR.message_types_by_name['ConfigValue'] = _CONFIGVALUE
DESCRIPTOR.message_types_by_name['ConfigDBSetEntryReq'] = _CONFIGDBSETENTRYREQ
DESCRIPTOR.message_types_by_name['ConfigDBGetEntryReq'] = _CONFIGDBGETENTRYREQ
DESCRIPTOR.message_types_by_name['ConfigDBSetEntryToDefaultReq'] = _CONFIGDBSETENTRYTODEFAULTREQ
DESCRIPTOR.message_types_by_name['ConfigEntryDataResp'] = _CONFIGENTRYDATARESP
DESCRIPTOR.message_types_by_name['ConfigDBInfoResp'] = _CONFIGDBINFORESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigValue = _reflection.GeneratedProtocolMessageType('ConfigValue', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGVALUE,
  '__module__' : 'ConfigDB_pb2'
  # @@protoc_insertion_point(class_scope:ConfigValue)
  })
_sym_db.RegisterMessage(ConfigValue)

ConfigDBSetEntryReq = _reflection.GeneratedProtocolMessageType('ConfigDBSetEntryReq', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGDBSETENTRYREQ,
  '__module__' : 'ConfigDB_pb2'
  # @@protoc_insertion_point(class_scope:ConfigDBSetEntryReq)
  })
_sym_db.RegisterMessage(ConfigDBSetEntryReq)

ConfigDBGetEntryReq = _reflection.GeneratedProtocolMessageType('ConfigDBGetEntryReq', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGDBGETENTRYREQ,
  '__module__' : 'ConfigDB_pb2'
  # @@protoc_insertion_point(class_scope:ConfigDBGetEntryReq)
  })
_sym_db.RegisterMessage(ConfigDBGetEntryReq)

ConfigDBSetEntryToDefaultReq = _reflection.GeneratedProtocolMessageType('ConfigDBSetEntryToDefaultReq', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGDBSETENTRYTODEFAULTREQ,
  '__module__' : 'ConfigDB_pb2'
  # @@protoc_insertion_point(class_scope:ConfigDBSetEntryToDefaultReq)
  })
_sym_db.RegisterMessage(ConfigDBSetEntryToDefaultReq)

ConfigEntryDataResp = _reflection.GeneratedProtocolMessageType('ConfigEntryDataResp', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGENTRYDATARESP,
  '__module__' : 'ConfigDB_pb2'
  # @@protoc_insertion_point(class_scope:ConfigEntryDataResp)
  })
_sym_db.RegisterMessage(ConfigEntryDataResp)

ConfigDBInfoResp = _reflection.GeneratedProtocolMessageType('ConfigDBInfoResp', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGDBINFORESP,
  '__module__' : 'ConfigDB_pb2'
  # @@protoc_insertion_point(class_scope:ConfigDBInfoResp)
  })
_sym_db.RegisterMessage(ConfigDBInfoResp)


# @@protoc_insertion_point(module_scope)
