# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: MessageType.proto

from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='MessageType.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11MessageType.proto*\xae\x02\n\x0bMessageType\x12\r\n\tLOG_PRINT\x10\x01\x12\x0c\n\x08\x43LI_DATA\x10\x02\x12\x1d\n\x19\x43ONFIG_DB_SAVE_TO_NVM_REQ\x10\x0b\x12#\n\x1f\x43ONFIG_DB_REQ_DATABASE_INFO_REQ\x10\x0c\x12$\n CONFIG_DB_SET_ALL_TO_DEFAULT_REQ\x10\r\x12\x1b\n\x17\x43ONFIG_DB_GET_ENTRY_REQ\x10\x0e\x12\x1b\n\x17\x43ONFIG_DB_SET_ENTRY_REQ\x10\x0f\x12&\n\"CONFIG_DB_SET_ENTRY_TO_DEFAULT_REQ\x10\x10\x12\x17\n\x13\x43ONFIG_DB_INFO_RESP\x10\x11\x12\x1d\n\x19\x43ONFIG_DB_ENTRY_DATA_RESP\x10\x12'
)

_MESSAGETYPE = _descriptor.EnumDescriptor(
  name='MessageType',
  full_name='MessageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOG_PRINT', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CLI_DATA', index=1, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_SAVE_TO_NVM_REQ', index=2, number=11,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_REQ_DATABASE_INFO_REQ', index=3, number=12,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_SET_ALL_TO_DEFAULT_REQ', index=4, number=13,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_GET_ENTRY_REQ', index=5, number=14,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_SET_ENTRY_REQ', index=6, number=15,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_SET_ENTRY_TO_DEFAULT_REQ', index=7, number=16,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_INFO_RESP', index=8, number=17,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='CONFIG_DB_ENTRY_DATA_RESP', index=9, number=18,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=22,
  serialized_end=324,
)
_sym_db.RegisterEnumDescriptor(_MESSAGETYPE)

MessageType = enum_type_wrapper.EnumTypeWrapper(_MESSAGETYPE)
LOG_PRINT = 1
CLI_DATA = 2
CONFIG_DB_SAVE_TO_NVM_REQ = 11
CONFIG_DB_REQ_DATABASE_INFO_REQ = 12
CONFIG_DB_SET_ALL_TO_DEFAULT_REQ = 13
CONFIG_DB_GET_ENTRY_REQ = 14
CONFIG_DB_SET_ENTRY_REQ = 15
CONFIG_DB_SET_ENTRY_TO_DEFAULT_REQ = 16
CONFIG_DB_INFO_RESP = 17
CONFIG_DB_ENTRY_DATA_RESP = 18


DESCRIPTOR.enum_types_by_name['MessageType'] = _MESSAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
